all:
	g++ beat.cpp  -F/Users/rickards/Downloads/sdk -framework myo -rpath /Users/rickards/Downloads/sdk -o beat
	g++ track.cpp  -F/Users/rickards/Downloads/sdk -framework myo -rpath /Users/rickards/Downloads/sdk -o track
